stages:
  - gateware
  - software

default:
  tags:
    - xilinx

variables:
  XILINX_VIVADO: /non-free/Xilinx/Vivado_and_Vitis/2022.2/Vivado/2022.2
  XILINX_VITIS: /non-free/Xilinx/Vivado_and_Vitis/2022.2/Vitis/2022.2
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  CI_REGISTRY: mohs2.dhcp.lbl.gov
  CONTAINER_IMAGE: $CI_REGISTRY/xilinx_env_bookworm
  GIT_SUBMODULE_STRATEGY: recursive
  FF_SCRIPT_SECTIONS: "true"

image: $CONTAINER_IMAGE:latest

# Gateware jobs
# Gitlab doesn't seem to suport the usage of variables in
# a "dependencies" or "needs" statement. So, unroll the job
# description, as to simplify job descriptions
gw_psc_picozed7030:
  before_script: |
    apt-get update && \
    apt-get install -y python3-venv
  stage: gateware
  script: |
    make env && \
    PATH=$XILINX_VIVADO/bin:$PATH make cfg=hw project && \
    PATH=$XILINX_VIVADO/bin:$PATH make cfg=hw build
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 4 weeks
    paths:
      - out/psc_hw/*

# Software jobs
# Gitlab doesn't seem to suport the usage of variables in
# a "dependencies" or "needs" statement. So, unroll the job
# description...
sw_psc_picozed7030:
  before_script: |
    apt-get update && \
    apt-get install -y python3-venv
  stage: software
  script: |
    make env && \
    PATH=$XILINX_VITIS/bin:$PATH make cfg=sw project && \
    PATH=$XILINX_VITIS/bin:$PATH make cfg=sw build
  # Get artifacts from this job, needed to compile the sofware
  needs:
    - job: gw_psc_picozed7030
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 4 weeks
    paths:
      - out/psc_sw/*
