create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list sys/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 9 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {read_dcct_adcs/dcct_adc1/bit_count[0]} {read_dcct_adcs/dcct_adc1/bit_count[1]} {read_dcct_adcs/dcct_adc1/bit_count[2]} {read_dcct_adcs/dcct_adc1/bit_count[3]} {read_dcct_adcs/dcct_adc1/bit_count[4]} {read_dcct_adcs/dcct_adc1/bit_count[5]} {read_dcct_adcs/dcct_adc1/bit_count[6]} {read_dcct_adcs/dcct_adc1/bit_count[7]} {read_dcct_adcs/dcct_adc1/bit_count[8]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 20 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {read_dcct_adcs/dcct_adc1/dcct1[0]} {read_dcct_adcs/dcct_adc1/dcct1[1]} {read_dcct_adcs/dcct_adc1/dcct1[2]} {read_dcct_adcs/dcct_adc1/dcct1[3]} {read_dcct_adcs/dcct_adc1/dcct1[4]} {read_dcct_adcs/dcct_adc1/dcct1[5]} {read_dcct_adcs/dcct_adc1/dcct1[6]} {read_dcct_adcs/dcct_adc1/dcct1[7]} {read_dcct_adcs/dcct_adc1/dcct1[8]} {read_dcct_adcs/dcct_adc1/dcct1[9]} {read_dcct_adcs/dcct_adc1/dcct1[10]} {read_dcct_adcs/dcct_adc1/dcct1[11]} {read_dcct_adcs/dcct_adc1/dcct1[12]} {read_dcct_adcs/dcct_adc1/dcct1[13]} {read_dcct_adcs/dcct_adc1/dcct1[14]} {read_dcct_adcs/dcct_adc1/dcct1[15]} {read_dcct_adcs/dcct_adc1/dcct1[16]} {read_dcct_adcs/dcct_adc1/dcct1[17]} {read_dcct_adcs/dcct_adc1/dcct1[18]} {read_dcct_adcs/dcct_adc1/dcct1[19]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 20 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {read_dcct_adcs/dcct_adc1/dcct2[0]} {read_dcct_adcs/dcct_adc1/dcct2[1]} {read_dcct_adcs/dcct_adc1/dcct2[2]} {read_dcct_adcs/dcct_adc1/dcct2[3]} {read_dcct_adcs/dcct_adc1/dcct2[4]} {read_dcct_adcs/dcct_adc1/dcct2[5]} {read_dcct_adcs/dcct_adc1/dcct2[6]} {read_dcct_adcs/dcct_adc1/dcct2[7]} {read_dcct_adcs/dcct_adc1/dcct2[8]} {read_dcct_adcs/dcct_adc1/dcct2[9]} {read_dcct_adcs/dcct_adc1/dcct2[10]} {read_dcct_adcs/dcct_adc1/dcct2[11]} {read_dcct_adcs/dcct_adc1/dcct2[12]} {read_dcct_adcs/dcct_adc1/dcct2[13]} {read_dcct_adcs/dcct_adc1/dcct2[14]} {read_dcct_adcs/dcct_adc1/dcct2[15]} {read_dcct_adcs/dcct_adc1/dcct2[16]} {read_dcct_adcs/dcct_adc1/dcct2[17]} {read_dcct_adcs/dcct_adc1/dcct2[18]} {read_dcct_adcs/dcct_adc1/dcct2[19]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 20 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {read_dcct_adcs/gainoff_adc1/dcct0_oc[0]} {read_dcct_adcs/gainoff_adc1/dcct0_oc[1]} {read_dcct_adcs/gainoff_adc1/dcct0_oc[2]} {read_dcct_adcs/gainoff_adc1/dcct0_oc[3]} {read_dcct_adcs/gainoff_adc1/dcct0_oc[4]} {read_dcct_adcs/gainoff_adc1/dcct0_oc[5]} {read_dcct_adcs/gainoff_adc1/dcct0_oc[6]} {read_dcct_adcs/gainoff_adc1/dcct0_oc[7]} {read_dcct_adcs/gainoff_adc1/dcct0_oc[8]} {read_dcct_adcs/gainoff_adc1/dcct0_oc[9]} {read_dcct_adcs/gainoff_adc1/dcct0_oc[10]} {read_dcct_adcs/gainoff_adc1/dcct0_oc[11]} {read_dcct_adcs/gainoff_adc1/dcct0_oc[12]} {read_dcct_adcs/gainoff_adc1/dcct0_oc[13]} {read_dcct_adcs/gainoff_adc1/dcct0_oc[14]} {read_dcct_adcs/gainoff_adc1/dcct0_oc[15]} {read_dcct_adcs/gainoff_adc1/dcct0_oc[16]} {read_dcct_adcs/gainoff_adc1/dcct0_oc[17]} {read_dcct_adcs/gainoff_adc1/dcct0_oc[18]} {read_dcct_adcs/gainoff_adc1/dcct0_oc[19]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {read_dcct_adcs/gainoff_adc1/dcct0_raw_f[0]} {read_dcct_adcs/gainoff_adc1/dcct0_raw_f[1]} {read_dcct_adcs/gainoff_adc1/dcct0_raw_f[2]} {read_dcct_adcs/gainoff_adc1/dcct0_raw_f[3]} {read_dcct_adcs/gainoff_adc1/dcct0_raw_f[4]} {read_dcct_adcs/gainoff_adc1/dcct0_raw_f[5]} {read_dcct_adcs/gainoff_adc1/dcct0_raw_f[6]} {read_dcct_adcs/gainoff_adc1/dcct0_raw_f[7]} {read_dcct_adcs/gainoff_adc1/dcct0_raw_f[8]} {read_dcct_adcs/gainoff_adc1/dcct0_raw_f[9]} {read_dcct_adcs/gainoff_adc1/dcct0_raw_f[10]} {read_dcct_adcs/gainoff_adc1/dcct0_raw_f[11]} {read_dcct_adcs/gainoff_adc1/dcct0_raw_f[12]} {read_dcct_adcs/gainoff_adc1/dcct0_raw_f[13]} {read_dcct_adcs/gainoff_adc1/dcct0_raw_f[14]} {read_dcct_adcs/gainoff_adc1/dcct0_raw_f[15]} {read_dcct_adcs/gainoff_adc1/dcct0_raw_f[16]} {read_dcct_adcs/gainoff_adc1/dcct0_raw_f[17]} {read_dcct_adcs/gainoff_adc1/dcct0_raw_f[18]} {read_dcct_adcs/gainoff_adc1/dcct0_raw_f[19]} {read_dcct_adcs/gainoff_adc1/dcct0_raw_f[20]} {read_dcct_adcs/gainoff_adc1/dcct0_raw_f[21]} {read_dcct_adcs/gainoff_adc1/dcct0_raw_f[22]} {read_dcct_adcs/gainoff_adc1/dcct0_raw_f[23]} {read_dcct_adcs/gainoff_adc1/dcct0_raw_f[24]} {read_dcct_adcs/gainoff_adc1/dcct0_raw_f[25]} {read_dcct_adcs/gainoff_adc1/dcct0_raw_f[26]} {read_dcct_adcs/gainoff_adc1/dcct0_raw_f[27]} {read_dcct_adcs/gainoff_adc1/dcct0_raw_f[28]} {read_dcct_adcs/gainoff_adc1/dcct0_raw_f[29]} {read_dcct_adcs/gainoff_adc1/dcct0_raw_f[30]} {read_dcct_adcs/gainoff_adc1/dcct0_raw_f[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {read_dcct_adcs/gainoff_adc1/dcct0_wgain_f[0]} {read_dcct_adcs/gainoff_adc1/dcct0_wgain_f[1]} {read_dcct_adcs/gainoff_adc1/dcct0_wgain_f[2]} {read_dcct_adcs/gainoff_adc1/dcct0_wgain_f[3]} {read_dcct_adcs/gainoff_adc1/dcct0_wgain_f[4]} {read_dcct_adcs/gainoff_adc1/dcct0_wgain_f[5]} {read_dcct_adcs/gainoff_adc1/dcct0_wgain_f[6]} {read_dcct_adcs/gainoff_adc1/dcct0_wgain_f[7]} {read_dcct_adcs/gainoff_adc1/dcct0_wgain_f[8]} {read_dcct_adcs/gainoff_adc1/dcct0_wgain_f[9]} {read_dcct_adcs/gainoff_adc1/dcct0_wgain_f[10]} {read_dcct_adcs/gainoff_adc1/dcct0_wgain_f[11]} {read_dcct_adcs/gainoff_adc1/dcct0_wgain_f[12]} {read_dcct_adcs/gainoff_adc1/dcct0_wgain_f[13]} {read_dcct_adcs/gainoff_adc1/dcct0_wgain_f[14]} {read_dcct_adcs/gainoff_adc1/dcct0_wgain_f[15]} {read_dcct_adcs/gainoff_adc1/dcct0_wgain_f[16]} {read_dcct_adcs/gainoff_adc1/dcct0_wgain_f[17]} {read_dcct_adcs/gainoff_adc1/dcct0_wgain_f[18]} {read_dcct_adcs/gainoff_adc1/dcct0_wgain_f[19]} {read_dcct_adcs/gainoff_adc1/dcct0_wgain_f[20]} {read_dcct_adcs/gainoff_adc1/dcct0_wgain_f[21]} {read_dcct_adcs/gainoff_adc1/dcct0_wgain_f[22]} {read_dcct_adcs/gainoff_adc1/dcct0_wgain_f[23]} {read_dcct_adcs/gainoff_adc1/dcct0_wgain_f[24]} {read_dcct_adcs/gainoff_adc1/dcct0_wgain_f[25]} {read_dcct_adcs/gainoff_adc1/dcct0_wgain_f[26]} {read_dcct_adcs/gainoff_adc1/dcct0_wgain_f[27]} {read_dcct_adcs/gainoff_adc1/dcct0_wgain_f[28]} {read_dcct_adcs/gainoff_adc1/dcct0_wgain_f[29]} {read_dcct_adcs/gainoff_adc1/dcct0_wgain_f[30]} {read_dcct_adcs/gainoff_adc1/dcct0_wgain_f[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 20 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {ps_regs/dcct_adcs[ps1][dcct0][0]} {ps_regs/dcct_adcs[ps1][dcct0][1]} {ps_regs/dcct_adcs[ps1][dcct0][2]} {ps_regs/dcct_adcs[ps1][dcct0][3]} {ps_regs/dcct_adcs[ps1][dcct0][4]} {ps_regs/dcct_adcs[ps1][dcct0][5]} {ps_regs/dcct_adcs[ps1][dcct0][6]} {ps_regs/dcct_adcs[ps1][dcct0][7]} {ps_regs/dcct_adcs[ps1][dcct0][8]} {ps_regs/dcct_adcs[ps1][dcct0][9]} {ps_regs/dcct_adcs[ps1][dcct0][10]} {ps_regs/dcct_adcs[ps1][dcct0][11]} {ps_regs/dcct_adcs[ps1][dcct0][12]} {ps_regs/dcct_adcs[ps1][dcct0][13]} {ps_regs/dcct_adcs[ps1][dcct0][14]} {ps_regs/dcct_adcs[ps1][dcct0][15]} {ps_regs/dcct_adcs[ps1][dcct0][16]} {ps_regs/dcct_adcs[ps1][dcct0][17]} {ps_regs/dcct_adcs[ps1][dcct0][18]} {ps_regs/dcct_adcs[ps1][dcct0][19]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 32 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {ps_regs/dcct_adcs[ps1][dcct0_fp][0]} {ps_regs/dcct_adcs[ps1][dcct0_fp][1]} {ps_regs/dcct_adcs[ps1][dcct0_fp][2]} {ps_regs/dcct_adcs[ps1][dcct0_fp][3]} {ps_regs/dcct_adcs[ps1][dcct0_fp][4]} {ps_regs/dcct_adcs[ps1][dcct0_fp][5]} {ps_regs/dcct_adcs[ps1][dcct0_fp][6]} {ps_regs/dcct_adcs[ps1][dcct0_fp][7]} {ps_regs/dcct_adcs[ps1][dcct0_fp][8]} {ps_regs/dcct_adcs[ps1][dcct0_fp][9]} {ps_regs/dcct_adcs[ps1][dcct0_fp][10]} {ps_regs/dcct_adcs[ps1][dcct0_fp][11]} {ps_regs/dcct_adcs[ps1][dcct0_fp][12]} {ps_regs/dcct_adcs[ps1][dcct0_fp][13]} {ps_regs/dcct_adcs[ps1][dcct0_fp][14]} {ps_regs/dcct_adcs[ps1][dcct0_fp][15]} {ps_regs/dcct_adcs[ps1][dcct0_fp][16]} {ps_regs/dcct_adcs[ps1][dcct0_fp][17]} {ps_regs/dcct_adcs[ps1][dcct0_fp][18]} {ps_regs/dcct_adcs[ps1][dcct0_fp][19]} {ps_regs/dcct_adcs[ps1][dcct0_fp][20]} {ps_regs/dcct_adcs[ps1][dcct0_fp][21]} {ps_regs/dcct_adcs[ps1][dcct0_fp][22]} {ps_regs/dcct_adcs[ps1][dcct0_fp][23]} {ps_regs/dcct_adcs[ps1][dcct0_fp][24]} {ps_regs/dcct_adcs[ps1][dcct0_fp][25]} {ps_regs/dcct_adcs[ps1][dcct0_fp][26]} {ps_regs/dcct_adcs[ps1][dcct0_fp][27]} {ps_regs/dcct_adcs[ps1][dcct0_fp][28]} {ps_regs/dcct_adcs[ps1][dcct0_fp][29]} {ps_regs/dcct_adcs[ps1][dcct0_fp][30]} {ps_regs/dcct_adcs[ps1][dcct0_fp][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 20 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {ps_regs/dcct_adcs[ps1][dcct0_raw][0]} {ps_regs/dcct_adcs[ps1][dcct0_raw][1]} {ps_regs/dcct_adcs[ps1][dcct0_raw][2]} {ps_regs/dcct_adcs[ps1][dcct0_raw][3]} {ps_regs/dcct_adcs[ps1][dcct0_raw][4]} {ps_regs/dcct_adcs[ps1][dcct0_raw][5]} {ps_regs/dcct_adcs[ps1][dcct0_raw][6]} {ps_regs/dcct_adcs[ps1][dcct0_raw][7]} {ps_regs/dcct_adcs[ps1][dcct0_raw][8]} {ps_regs/dcct_adcs[ps1][dcct0_raw][9]} {ps_regs/dcct_adcs[ps1][dcct0_raw][10]} {ps_regs/dcct_adcs[ps1][dcct0_raw][11]} {ps_regs/dcct_adcs[ps1][dcct0_raw][12]} {ps_regs/dcct_adcs[ps1][dcct0_raw][13]} {ps_regs/dcct_adcs[ps1][dcct0_raw][14]} {ps_regs/dcct_adcs[ps1][dcct0_raw][15]} {ps_regs/dcct_adcs[ps1][dcct0_raw][16]} {ps_regs/dcct_adcs[ps1][dcct0_raw][17]} {ps_regs/dcct_adcs[ps1][dcct0_raw][18]} {ps_regs/dcct_adcs[ps1][dcct0_raw][19]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 20 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {ps_regs/dcct_adcs[ps1][dcct1][0]} {ps_regs/dcct_adcs[ps1][dcct1][1]} {ps_regs/dcct_adcs[ps1][dcct1][2]} {ps_regs/dcct_adcs[ps1][dcct1][3]} {ps_regs/dcct_adcs[ps1][dcct1][4]} {ps_regs/dcct_adcs[ps1][dcct1][5]} {ps_regs/dcct_adcs[ps1][dcct1][6]} {ps_regs/dcct_adcs[ps1][dcct1][7]} {ps_regs/dcct_adcs[ps1][dcct1][8]} {ps_regs/dcct_adcs[ps1][dcct1][9]} {ps_regs/dcct_adcs[ps1][dcct1][10]} {ps_regs/dcct_adcs[ps1][dcct1][11]} {ps_regs/dcct_adcs[ps1][dcct1][12]} {ps_regs/dcct_adcs[ps1][dcct1][13]} {ps_regs/dcct_adcs[ps1][dcct1][14]} {ps_regs/dcct_adcs[ps1][dcct1][15]} {ps_regs/dcct_adcs[ps1][dcct1][16]} {ps_regs/dcct_adcs[ps1][dcct1][17]} {ps_regs/dcct_adcs[ps1][dcct1][18]} {ps_regs/dcct_adcs[ps1][dcct1][19]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 32 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {ps_regs/dcct_params[ps1][dcct0_gain][0]} {ps_regs/dcct_params[ps1][dcct0_gain][1]} {ps_regs/dcct_params[ps1][dcct0_gain][2]} {ps_regs/dcct_params[ps1][dcct0_gain][3]} {ps_regs/dcct_params[ps1][dcct0_gain][4]} {ps_regs/dcct_params[ps1][dcct0_gain][5]} {ps_regs/dcct_params[ps1][dcct0_gain][6]} {ps_regs/dcct_params[ps1][dcct0_gain][7]} {ps_regs/dcct_params[ps1][dcct0_gain][8]} {ps_regs/dcct_params[ps1][dcct0_gain][9]} {ps_regs/dcct_params[ps1][dcct0_gain][10]} {ps_regs/dcct_params[ps1][dcct0_gain][11]} {ps_regs/dcct_params[ps1][dcct0_gain][12]} {ps_regs/dcct_params[ps1][dcct0_gain][13]} {ps_regs/dcct_params[ps1][dcct0_gain][14]} {ps_regs/dcct_params[ps1][dcct0_gain][15]} {ps_regs/dcct_params[ps1][dcct0_gain][16]} {ps_regs/dcct_params[ps1][dcct0_gain][17]} {ps_regs/dcct_params[ps1][dcct0_gain][18]} {ps_regs/dcct_params[ps1][dcct0_gain][19]} {ps_regs/dcct_params[ps1][dcct0_gain][20]} {ps_regs/dcct_params[ps1][dcct0_gain][21]} {ps_regs/dcct_params[ps1][dcct0_gain][22]} {ps_regs/dcct_params[ps1][dcct0_gain][23]} {ps_regs/dcct_params[ps1][dcct0_gain][24]} {ps_regs/dcct_params[ps1][dcct0_gain][25]} {ps_regs/dcct_params[ps1][dcct0_gain][26]} {ps_regs/dcct_params[ps1][dcct0_gain][27]} {ps_regs/dcct_params[ps1][dcct0_gain][28]} {ps_regs/dcct_params[ps1][dcct0_gain][29]} {ps_regs/dcct_params[ps1][dcct0_gain][30]} {ps_regs/dcct_params[ps1][dcct0_gain][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 20 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {ps_regs/dcct_params[ps1][dcct0_offset][0]} {ps_regs/dcct_params[ps1][dcct0_offset][1]} {ps_regs/dcct_params[ps1][dcct0_offset][2]} {ps_regs/dcct_params[ps1][dcct0_offset][3]} {ps_regs/dcct_params[ps1][dcct0_offset][4]} {ps_regs/dcct_params[ps1][dcct0_offset][5]} {ps_regs/dcct_params[ps1][dcct0_offset][6]} {ps_regs/dcct_params[ps1][dcct0_offset][7]} {ps_regs/dcct_params[ps1][dcct0_offset][8]} {ps_regs/dcct_params[ps1][dcct0_offset][9]} {ps_regs/dcct_params[ps1][dcct0_offset][10]} {ps_regs/dcct_params[ps1][dcct0_offset][11]} {ps_regs/dcct_params[ps1][dcct0_offset][12]} {ps_regs/dcct_params[ps1][dcct0_offset][13]} {ps_regs/dcct_params[ps1][dcct0_offset][14]} {ps_regs/dcct_params[ps1][dcct0_offset][15]} {ps_regs/dcct_params[ps1][dcct0_offset][16]} {ps_regs/dcct_params[ps1][dcct0_offset][17]} {ps_regs/dcct_params[ps1][dcct0_offset][18]} {ps_regs/dcct_params[ps1][dcct0_offset][19]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 32 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {ps_regs/dcct_params[ps1][dcct1_gain][0]} {ps_regs/dcct_params[ps1][dcct1_gain][1]} {ps_regs/dcct_params[ps1][dcct1_gain][2]} {ps_regs/dcct_params[ps1][dcct1_gain][3]} {ps_regs/dcct_params[ps1][dcct1_gain][4]} {ps_regs/dcct_params[ps1][dcct1_gain][5]} {ps_regs/dcct_params[ps1][dcct1_gain][6]} {ps_regs/dcct_params[ps1][dcct1_gain][7]} {ps_regs/dcct_params[ps1][dcct1_gain][8]} {ps_regs/dcct_params[ps1][dcct1_gain][9]} {ps_regs/dcct_params[ps1][dcct1_gain][10]} {ps_regs/dcct_params[ps1][dcct1_gain][11]} {ps_regs/dcct_params[ps1][dcct1_gain][12]} {ps_regs/dcct_params[ps1][dcct1_gain][13]} {ps_regs/dcct_params[ps1][dcct1_gain][14]} {ps_regs/dcct_params[ps1][dcct1_gain][15]} {ps_regs/dcct_params[ps1][dcct1_gain][16]} {ps_regs/dcct_params[ps1][dcct1_gain][17]} {ps_regs/dcct_params[ps1][dcct1_gain][18]} {ps_regs/dcct_params[ps1][dcct1_gain][19]} {ps_regs/dcct_params[ps1][dcct1_gain][20]} {ps_regs/dcct_params[ps1][dcct1_gain][21]} {ps_regs/dcct_params[ps1][dcct1_gain][22]} {ps_regs/dcct_params[ps1][dcct1_gain][23]} {ps_regs/dcct_params[ps1][dcct1_gain][24]} {ps_regs/dcct_params[ps1][dcct1_gain][25]} {ps_regs/dcct_params[ps1][dcct1_gain][26]} {ps_regs/dcct_params[ps1][dcct1_gain][27]} {ps_regs/dcct_params[ps1][dcct1_gain][28]} {ps_regs/dcct_params[ps1][dcct1_gain][29]} {ps_regs/dcct_params[ps1][dcct1_gain][30]} {ps_regs/dcct_params[ps1][dcct1_gain][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 20 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list {ps_regs/dcct_params[ps1][dcct1_offset][0]} {ps_regs/dcct_params[ps1][dcct1_offset][1]} {ps_regs/dcct_params[ps1][dcct1_offset][2]} {ps_regs/dcct_params[ps1][dcct1_offset][3]} {ps_regs/dcct_params[ps1][dcct1_offset][4]} {ps_regs/dcct_params[ps1][dcct1_offset][5]} {ps_regs/dcct_params[ps1][dcct1_offset][6]} {ps_regs/dcct_params[ps1][dcct1_offset][7]} {ps_regs/dcct_params[ps1][dcct1_offset][8]} {ps_regs/dcct_params[ps1][dcct1_offset][9]} {ps_regs/dcct_params[ps1][dcct1_offset][10]} {ps_regs/dcct_params[ps1][dcct1_offset][11]} {ps_regs/dcct_params[ps1][dcct1_offset][12]} {ps_regs/dcct_params[ps1][dcct1_offset][13]} {ps_regs/dcct_params[ps1][dcct1_offset][14]} {ps_regs/dcct_params[ps1][dcct1_offset][15]} {ps_regs/dcct_params[ps1][dcct1_offset][16]} {ps_regs/dcct_params[ps1][dcct1_offset][17]} {ps_regs/dcct_params[ps1][dcct1_offset][18]} {ps_regs/dcct_params[ps1][dcct1_offset][19]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list write_dacs/tenkhz_trig]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list read_dcct_adcs/dcct_adc1/cnv]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list read_dcct_adcs/dcct_adc1/data_rdy]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets pl_clk0]
