create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list fofb/fofb_phy/phy_sfp0_rx/U0/core_clocking_i/userclk2]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 20 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {fofb/ps1/fofb_setpt[0]} {fofb/ps1/fofb_setpt[1]} {fofb/ps1/fofb_setpt[2]} {fofb/ps1/fofb_setpt[3]} {fofb/ps1/fofb_setpt[4]} {fofb/ps1/fofb_setpt[5]} {fofb/ps1/fofb_setpt[6]} {fofb/ps1/fofb_setpt[7]} {fofb/ps1/fofb_setpt[8]} {fofb/ps1/fofb_setpt[9]} {fofb/ps1/fofb_setpt[10]} {fofb/ps1/fofb_setpt[11]} {fofb/ps1/fofb_setpt[12]} {fofb/ps1/fofb_setpt[13]} {fofb/ps1/fofb_setpt[14]} {fofb/ps1/fofb_setpt[15]} {fofb/ps1/fofb_setpt[16]} {fofb/ps1/fofb_setpt[17]} {fofb/ps1/fofb_setpt[18]} {fofb/ps1/fofb_setpt[19]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {fofb/ps1/setpt_scaled[0]} {fofb/ps1/setpt_scaled[1]} {fofb/ps1/setpt_scaled[2]} {fofb/ps1/setpt_scaled[3]} {fofb/ps1/setpt_scaled[4]} {fofb/ps1/setpt_scaled[5]} {fofb/ps1/setpt_scaled[6]} {fofb/ps1/setpt_scaled[7]} {fofb/ps1/setpt_scaled[8]} {fofb/ps1/setpt_scaled[9]} {fofb/ps1/setpt_scaled[10]} {fofb/ps1/setpt_scaled[11]} {fofb/ps1/setpt_scaled[12]} {fofb/ps1/setpt_scaled[13]} {fofb/ps1/setpt_scaled[14]} {fofb/ps1/setpt_scaled[15]} {fofb/ps1/setpt_scaled[16]} {fofb/ps1/setpt_scaled[17]} {fofb/ps1/setpt_scaled[18]} {fofb/ps1/setpt_scaled[19]} {fofb/ps1/setpt_scaled[20]} {fofb/ps1/setpt_scaled[21]} {fofb/ps1/setpt_scaled[22]} {fofb/ps1/setpt_scaled[23]} {fofb/ps1/setpt_scaled[24]} {fofb/ps1/setpt_scaled[25]} {fofb/ps1/setpt_scaled[26]} {fofb/ps1/setpt_scaled[27]} {fofb/ps1/setpt_scaled[28]} {fofb/ps1/setpt_scaled[29]} {fofb/ps1/setpt_scaled[30]} {fofb/ps1/setpt_scaled[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 24 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {fofb/ps1/setptout_fp[0]} {fofb/ps1/setptout_fp[1]} {fofb/ps1/setptout_fp[2]} {fofb/ps1/setptout_fp[3]} {fofb/ps1/setptout_fp[4]} {fofb/ps1/setptout_fp[5]} {fofb/ps1/setptout_fp[6]} {fofb/ps1/setptout_fp[7]} {fofb/ps1/setptout_fp[8]} {fofb/ps1/setptout_fp[9]} {fofb/ps1/setptout_fp[10]} {fofb/ps1/setptout_fp[11]} {fofb/ps1/setptout_fp[12]} {fofb/ps1/setptout_fp[13]} {fofb/ps1/setptout_fp[14]} {fofb/ps1/setptout_fp[15]} {fofb/ps1/setptout_fp[16]} {fofb/ps1/setptout_fp[17]} {fofb/ps1/setptout_fp[18]} {fofb/ps1/setptout_fp[19]} {fofb/ps1/setptout_fp[20]} {fofb/ps1/setptout_fp[21]} {fofb/ps1/setptout_fp[22]} {fofb/ps1/setptout_fp[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 15 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {fofb/fofb_rcv/framebytenum[0]} {fofb/fofb_rcv/framebytenum[1]} {fofb/fofb_rcv/framebytenum[2]} {fofb/fofb_rcv/framebytenum[3]} {fofb/fofb_rcv/framebytenum[4]} {fofb/fofb_rcv/framebytenum[5]} {fofb/fofb_rcv/framebytenum[6]} {fofb/fofb_rcv/framebytenum[7]} {fofb/fofb_rcv/framebytenum[8]} {fofb/fofb_rcv/framebytenum[9]} {fofb/fofb_rcv/framebytenum[10]} {fofb/fofb_rcv/framebytenum[11]} {fofb/fofb_rcv/framebytenum[12]} {fofb/fofb_rcv/framebytenum[13]} {fofb/fofb_rcv/framebytenum[14]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 4 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {fofb/fofb_rcv/state[0]} {fofb/fofb_rcv/state[1]} {fofb/fofb_rcv/state[2]} {fofb/fofb_rcv/state[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 16 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {fofb/fofb_rcv/udp_pkt_buf_rx[fast_ps_id][0]} {fofb/fofb_rcv/udp_pkt_buf_rx[fast_ps_id][1]} {fofb/fofb_rcv/udp_pkt_buf_rx[fast_ps_id][2]} {fofb/fofb_rcv/udp_pkt_buf_rx[fast_ps_id][3]} {fofb/fofb_rcv/udp_pkt_buf_rx[fast_ps_id][4]} {fofb/fofb_rcv/udp_pkt_buf_rx[fast_ps_id][5]} {fofb/fofb_rcv/udp_pkt_buf_rx[fast_ps_id][6]} {fofb/fofb_rcv/udp_pkt_buf_rx[fast_ps_id][7]} {fofb/fofb_rcv/udp_pkt_buf_rx[fast_ps_id][8]} {fofb/fofb_rcv/udp_pkt_buf_rx[fast_ps_id][9]} {fofb/fofb_rcv/udp_pkt_buf_rx[fast_ps_id][10]} {fofb/fofb_rcv/udp_pkt_buf_rx[fast_ps_id][11]} {fofb/fofb_rcv/udp_pkt_buf_rx[fast_ps_id][12]} {fofb/fofb_rcv/udp_pkt_buf_rx[fast_ps_id][13]} {fofb/fofb_rcv/udp_pkt_buf_rx[fast_ps_id][14]} {fofb/fofb_rcv/udp_pkt_buf_rx[fast_ps_id][15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 16 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {fofb/fofb_rcv/udp_pkt_buf_rx[header_checksum][0]} {fofb/fofb_rcv/udp_pkt_buf_rx[header_checksum][1]} {fofb/fofb_rcv/udp_pkt_buf_rx[header_checksum][2]} {fofb/fofb_rcv/udp_pkt_buf_rx[header_checksum][3]} {fofb/fofb_rcv/udp_pkt_buf_rx[header_checksum][4]} {fofb/fofb_rcv/udp_pkt_buf_rx[header_checksum][5]} {fofb/fofb_rcv/udp_pkt_buf_rx[header_checksum][6]} {fofb/fofb_rcv/udp_pkt_buf_rx[header_checksum][7]} {fofb/fofb_rcv/udp_pkt_buf_rx[header_checksum][8]} {fofb/fofb_rcv/udp_pkt_buf_rx[header_checksum][9]} {fofb/fofb_rcv/udp_pkt_buf_rx[header_checksum][10]} {fofb/fofb_rcv/udp_pkt_buf_rx[header_checksum][11]} {fofb/fofb_rcv/udp_pkt_buf_rx[header_checksum][12]} {fofb/fofb_rcv/udp_pkt_buf_rx[header_checksum][13]} {fofb/fofb_rcv/udp_pkt_buf_rx[header_checksum][14]} {fofb/fofb_rcv/udp_pkt_buf_rx[header_checksum][15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 32 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {fofb/fofb_rcv/udp_pkt_buf_rx[ip_dest_addr][0]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_dest_addr][1]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_dest_addr][2]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_dest_addr][3]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_dest_addr][4]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_dest_addr][5]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_dest_addr][6]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_dest_addr][7]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_dest_addr][8]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_dest_addr][9]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_dest_addr][10]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_dest_addr][11]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_dest_addr][12]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_dest_addr][13]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_dest_addr][14]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_dest_addr][15]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_dest_addr][16]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_dest_addr][17]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_dest_addr][18]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_dest_addr][19]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_dest_addr][20]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_dest_addr][21]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_dest_addr][22]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_dest_addr][23]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_dest_addr][24]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_dest_addr][25]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_dest_addr][26]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_dest_addr][27]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_dest_addr][28]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_dest_addr][29]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_dest_addr][30]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_dest_addr][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 3 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {fofb/fofb_rcv/udp_pkt_buf_rx[ip_flags][0]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_flags][1]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_flags][2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 13 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {fofb/fofb_rcv/udp_pkt_buf_rx[ip_fragoffset][0]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_fragoffset][1]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_fragoffset][2]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_fragoffset][3]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_fragoffset][4]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_fragoffset][5]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_fragoffset][6]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_fragoffset][7]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_fragoffset][8]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_fragoffset][9]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_fragoffset][10]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_fragoffset][11]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_fragoffset][12]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 16 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {fofb/fofb_rcv/udp_pkt_buf_rx[ip_ident][0]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_ident][1]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_ident][2]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_ident][3]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_ident][4]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_ident][5]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_ident][6]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_ident][7]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_ident][8]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_ident][9]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_ident][10]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_ident][11]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_ident][12]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_ident][13]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_ident][14]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_ident][15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 4 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {fofb/fofb_rcv/udp_pkt_buf_rx[ip_ihl][0]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_ihl][1]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_ihl][2]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_ihl][3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 8 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {fofb/fofb_rcv/udp_pkt_buf_rx[ip_protocol][0]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_protocol][1]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_protocol][2]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_protocol][3]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_protocol][4]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_protocol][5]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_protocol][6]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_protocol][7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 32 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list {fofb/fofb_rcv/udp_pkt_buf_rx[ip_src_addr][0]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_src_addr][1]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_src_addr][2]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_src_addr][3]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_src_addr][4]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_src_addr][5]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_src_addr][6]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_src_addr][7]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_src_addr][8]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_src_addr][9]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_src_addr][10]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_src_addr][11]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_src_addr][12]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_src_addr][13]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_src_addr][14]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_src_addr][15]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_src_addr][16]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_src_addr][17]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_src_addr][18]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_src_addr][19]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_src_addr][20]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_src_addr][21]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_src_addr][22]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_src_addr][23]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_src_addr][24]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_src_addr][25]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_src_addr][26]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_src_addr][27]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_src_addr][28]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_src_addr][29]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_src_addr][30]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_src_addr][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 8 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list {fofb/fofb_rcv/udp_pkt_buf_rx[ip_tos][0]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_tos][1]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_tos][2]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_tos][3]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_tos][4]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_tos][5]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_tos][6]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_tos][7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 8 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list {fofb/fofb_rcv/udp_pkt_buf_rx[ip_ttl][0]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_ttl][1]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_ttl][2]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_ttl][3]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_ttl][4]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_ttl][5]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_ttl][6]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_ttl][7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 4 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list {fofb/fofb_rcv/udp_pkt_buf_rx[ip_ver][0]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_ver][1]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_ver][2]} {fofb/fofb_rcv/udp_pkt_buf_rx[ip_ver][3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 48 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][0]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][1]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][2]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][3]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][4]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][5]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][6]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][7]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][8]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][9]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][10]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][11]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][12]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][13]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][14]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][15]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][16]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][17]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][18]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][19]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][20]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][21]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][22]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][23]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][24]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][25]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][26]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][27]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][28]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][29]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][30]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][31]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][32]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][33]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][34]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][35]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][36]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][37]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][38]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][39]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][40]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][41]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][42]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][43]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][44]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][45]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][46]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_dest_addr][47]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 16 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list {fofb/fofb_rcv/udp_pkt_buf_rx[mac_len_type][0]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_len_type][1]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_len_type][2]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_len_type][3]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_len_type][4]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_len_type][5]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_len_type][6]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_len_type][7]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_len_type][8]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_len_type][9]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_len_type][10]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_len_type][11]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_len_type][12]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_len_type][13]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_len_type][14]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_len_type][15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 48 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][0]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][1]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][2]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][3]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][4]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][5]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][6]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][7]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][8]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][9]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][10]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][11]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][12]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][13]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][14]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][15]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][16]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][17]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][18]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][19]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][20]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][21]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][22]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][23]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][24]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][25]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][26]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][27]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][28]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][29]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][30]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][31]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][32]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][33]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][34]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][35]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][36]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][37]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][38]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][39]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][40]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][41]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][42]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][43]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][44]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][45]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][46]} {fofb/fofb_rcv/udp_pkt_buf_rx[mac_src_addr][47]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 64 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][0]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][1]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][2]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][3]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][4]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][5]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][6]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][7]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][8]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][9]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][10]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][11]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][12]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][13]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][14]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][15]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][16]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][17]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][18]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][19]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][20]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][21]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][22]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][23]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][24]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][25]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][26]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][27]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][28]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][29]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][30]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][31]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][32]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][33]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][34]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][35]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][36]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][37]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][38]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][39]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][40]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][41]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][42]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][43]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][44]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][45]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][46]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][47]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][48]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][49]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][50]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][51]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][52]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][53]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][54]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][55]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][56]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][57]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][58]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][59]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][60]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][61]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][62]} {fofb/fofb_rcv/udp_pkt_buf_rx[nonce][63]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 16 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list {fofb/fofb_rcv/udp_pkt_buf_rx[readback_cmd][0]} {fofb/fofb_rcv/udp_pkt_buf_rx[readback_cmd][1]} {fofb/fofb_rcv/udp_pkt_buf_rx[readback_cmd][2]} {fofb/fofb_rcv/udp_pkt_buf_rx[readback_cmd][3]} {fofb/fofb_rcv/udp_pkt_buf_rx[readback_cmd][4]} {fofb/fofb_rcv/udp_pkt_buf_rx[readback_cmd][5]} {fofb/fofb_rcv/udp_pkt_buf_rx[readback_cmd][6]} {fofb/fofb_rcv/udp_pkt_buf_rx[readback_cmd][7]} {fofb/fofb_rcv/udp_pkt_buf_rx[readback_cmd][8]} {fofb/fofb_rcv/udp_pkt_buf_rx[readback_cmd][9]} {fofb/fofb_rcv/udp_pkt_buf_rx[readback_cmd][10]} {fofb/fofb_rcv/udp_pkt_buf_rx[readback_cmd][11]} {fofb/fofb_rcv/udp_pkt_buf_rx[readback_cmd][12]} {fofb/fofb_rcv/udp_pkt_buf_rx[readback_cmd][13]} {fofb/fofb_rcv/udp_pkt_buf_rx[readback_cmd][14]} {fofb/fofb_rcv/udp_pkt_buf_rx[readback_cmd][15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 16 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list {fofb/fofb_rcv/udp_pkt_buf_rx[total_len][0]} {fofb/fofb_rcv/udp_pkt_buf_rx[total_len][1]} {fofb/fofb_rcv/udp_pkt_buf_rx[total_len][2]} {fofb/fofb_rcv/udp_pkt_buf_rx[total_len][3]} {fofb/fofb_rcv/udp_pkt_buf_rx[total_len][4]} {fofb/fofb_rcv/udp_pkt_buf_rx[total_len][5]} {fofb/fofb_rcv/udp_pkt_buf_rx[total_len][6]} {fofb/fofb_rcv/udp_pkt_buf_rx[total_len][7]} {fofb/fofb_rcv/udp_pkt_buf_rx[total_len][8]} {fofb/fofb_rcv/udp_pkt_buf_rx[total_len][9]} {fofb/fofb_rcv/udp_pkt_buf_rx[total_len][10]} {fofb/fofb_rcv/udp_pkt_buf_rx[total_len][11]} {fofb/fofb_rcv/udp_pkt_buf_rx[total_len][12]} {fofb/fofb_rcv/udp_pkt_buf_rx[total_len][13]} {fofb/fofb_rcv/udp_pkt_buf_rx[total_len][14]} {fofb/fofb_rcv/udp_pkt_buf_rx[total_len][15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property port_width 16 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list {fofb/fofb_rcv/udp_pkt_buf_rx[udp_checksum][0]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_checksum][1]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_checksum][2]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_checksum][3]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_checksum][4]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_checksum][5]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_checksum][6]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_checksum][7]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_checksum][8]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_checksum][9]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_checksum][10]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_checksum][11]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_checksum][12]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_checksum][13]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_checksum][14]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_checksum][15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property port_width 16 [get_debug_ports u_ila_0/probe24]
connect_debug_port u_ila_0/probe24 [get_nets [list {fofb/fofb_rcv/udp_pkt_buf_rx[udp_dest_port][0]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_dest_port][1]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_dest_port][2]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_dest_port][3]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_dest_port][4]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_dest_port][5]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_dest_port][6]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_dest_port][7]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_dest_port][8]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_dest_port][9]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_dest_port][10]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_dest_port][11]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_dest_port][12]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_dest_port][13]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_dest_port][14]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_dest_port][15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property port_width 16 [get_debug_ports u_ila_0/probe25]
connect_debug_port u_ila_0/probe25 [get_nets [list {fofb/fofb_rcv/udp_pkt_buf_rx[udp_len][0]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_len][1]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_len][2]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_len][3]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_len][4]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_len][5]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_len][6]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_len][7]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_len][8]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_len][9]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_len][10]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_len][11]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_len][12]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_len][13]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_len][14]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_len][15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property port_width 16 [get_debug_ports u_ila_0/probe26]
connect_debug_port u_ila_0/probe26 [get_nets [list {fofb/fofb_rcv/udp_pkt_buf_rx[udp_src_port][0]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_src_port][1]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_src_port][2]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_src_port][3]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_src_port][4]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_src_port][5]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_src_port][6]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_src_port][7]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_src_port][8]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_src_port][9]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_src_port][10]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_src_port][11]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_src_port][12]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_src_port][13]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_src_port][14]} {fofb/fofb_rcv/udp_pkt_buf_rx[udp_src_port][15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property port_width 20 [get_debug_ports u_ila_0/probe27]
connect_debug_port u_ila_0/probe27 [get_nets [list {fofb/fofb_data[ps1_setpt][0]} {fofb/fofb_data[ps1_setpt][1]} {fofb/fofb_data[ps1_setpt][2]} {fofb/fofb_data[ps1_setpt][3]} {fofb/fofb_data[ps1_setpt][4]} {fofb/fofb_data[ps1_setpt][5]} {fofb/fofb_data[ps1_setpt][6]} {fofb/fofb_data[ps1_setpt][7]} {fofb/fofb_data[ps1_setpt][8]} {fofb/fofb_data[ps1_setpt][9]} {fofb/fofb_data[ps1_setpt][10]} {fofb/fofb_data[ps1_setpt][11]} {fofb/fofb_data[ps1_setpt][12]} {fofb/fofb_data[ps1_setpt][13]} {fofb/fofb_data[ps1_setpt][14]} {fofb/fofb_data[ps1_setpt][15]} {fofb/fofb_data[ps1_setpt][16]} {fofb/fofb_data[ps1_setpt][17]} {fofb/fofb_data[ps1_setpt][18]} {fofb/fofb_data[ps1_setpt][19]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property port_width 32 [get_debug_ports u_ila_0/probe28]
connect_debug_port u_ila_0/probe28 [get_nets [list {fofb/fofb_params[ipaddr][0]} {fofb/fofb_params[ipaddr][1]} {fofb/fofb_params[ipaddr][2]} {fofb/fofb_params[ipaddr][3]} {fofb/fofb_params[ipaddr][4]} {fofb/fofb_params[ipaddr][5]} {fofb/fofb_params[ipaddr][6]} {fofb/fofb_params[ipaddr][7]} {fofb/fofb_params[ipaddr][8]} {fofb/fofb_params[ipaddr][9]} {fofb/fofb_params[ipaddr][10]} {fofb/fofb_params[ipaddr][11]} {fofb/fofb_params[ipaddr][12]} {fofb/fofb_params[ipaddr][13]} {fofb/fofb_params[ipaddr][14]} {fofb/fofb_params[ipaddr][15]} {fofb/fofb_params[ipaddr][16]} {fofb/fofb_params[ipaddr][17]} {fofb/fofb_params[ipaddr][18]} {fofb/fofb_params[ipaddr][19]} {fofb/fofb_params[ipaddr][20]} {fofb/fofb_params[ipaddr][21]} {fofb/fofb_params[ipaddr][22]} {fofb/fofb_params[ipaddr][23]} {fofb/fofb_params[ipaddr][24]} {fofb/fofb_params[ipaddr][25]} {fofb/fofb_params[ipaddr][26]} {fofb/fofb_params[ipaddr][27]} {fofb/fofb_params[ipaddr][28]} {fofb/fofb_params[ipaddr][29]} {fofb/fofb_params[ipaddr][30]} {fofb/fofb_params[ipaddr][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
set_property port_width 16 [get_debug_ports u_ila_0/probe29]
connect_debug_port u_ila_0/probe29 [get_nets [list {fofb/fofb_params[ps1_addr][0]} {fofb/fofb_params[ps1_addr][1]} {fofb/fofb_params[ps1_addr][2]} {fofb/fofb_params[ps1_addr][3]} {fofb/fofb_params[ps1_addr][4]} {fofb/fofb_params[ps1_addr][5]} {fofb/fofb_params[ps1_addr][6]} {fofb/fofb_params[ps1_addr][7]} {fofb/fofb_params[ps1_addr][8]} {fofb/fofb_params[ps1_addr][9]} {fofb/fofb_params[ps1_addr][10]} {fofb/fofb_params[ps1_addr][11]} {fofb/fofb_params[ps1_addr][12]} {fofb/fofb_params[ps1_addr][13]} {fofb/fofb_params[ps1_addr][14]} {fofb/fofb_params[ps1_addr][15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe30]
set_property port_width 32 [get_debug_ports u_ila_0/probe30]
connect_debug_port u_ila_0/probe30 [get_nets [list {fofb/fofb_params[ps1_scalefactor][0]} {fofb/fofb_params[ps1_scalefactor][1]} {fofb/fofb_params[ps1_scalefactor][2]} {fofb/fofb_params[ps1_scalefactor][3]} {fofb/fofb_params[ps1_scalefactor][4]} {fofb/fofb_params[ps1_scalefactor][5]} {fofb/fofb_params[ps1_scalefactor][6]} {fofb/fofb_params[ps1_scalefactor][7]} {fofb/fofb_params[ps1_scalefactor][8]} {fofb/fofb_params[ps1_scalefactor][9]} {fofb/fofb_params[ps1_scalefactor][10]} {fofb/fofb_params[ps1_scalefactor][11]} {fofb/fofb_params[ps1_scalefactor][12]} {fofb/fofb_params[ps1_scalefactor][13]} {fofb/fofb_params[ps1_scalefactor][14]} {fofb/fofb_params[ps1_scalefactor][15]} {fofb/fofb_params[ps1_scalefactor][16]} {fofb/fofb_params[ps1_scalefactor][17]} {fofb/fofb_params[ps1_scalefactor][18]} {fofb/fofb_params[ps1_scalefactor][19]} {fofb/fofb_params[ps1_scalefactor][20]} {fofb/fofb_params[ps1_scalefactor][21]} {fofb/fofb_params[ps1_scalefactor][22]} {fofb/fofb_params[ps1_scalefactor][23]} {fofb/fofb_params[ps1_scalefactor][24]} {fofb/fofb_params[ps1_scalefactor][25]} {fofb/fofb_params[ps1_scalefactor][26]} {fofb/fofb_params[ps1_scalefactor][27]} {fofb/fofb_params[ps1_scalefactor][28]} {fofb/fofb_params[ps1_scalefactor][29]} {fofb/fofb_params[ps1_scalefactor][30]} {fofb/fofb_params[ps1_scalefactor][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe31]
set_property port_width 8 [get_debug_ports u_ila_0/probe31]
connect_debug_port u_ila_0/probe31 [get_nets [list {fofb/fofb_rxd[0]} {fofb/fofb_rxd[1]} {fofb/fofb_rxd[2]} {fofb/fofb_rxd[3]} {fofb/fofb_rxd[4]} {fofb/fofb_rxd[5]} {fofb/fofb_rxd[6]} {fofb/fofb_rxd[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe32]
set_property port_width 8 [get_debug_ports u_ila_0/probe32]
connect_debug_port u_ila_0/probe32 [get_nets [list {fofb/fofb_rxd_dly[0]} {fofb/fofb_rxd_dly[1]} {fofb/fofb_rxd_dly[2]} {fofb/fofb_rxd_dly[3]} {fofb/fofb_rxd_dly[4]} {fofb/fofb_rxd_dly[5]} {fofb/fofb_rxd_dly[6]} {fofb/fofb_rxd_dly[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe33]
set_property port_width 32 [get_debug_ports u_ila_0/probe33]
connect_debug_port u_ila_0/probe33 [get_nets [list {fofb/fofb_stat[nonce][0]} {fofb/fofb_stat[nonce][1]} {fofb/fofb_stat[nonce][2]} {fofb/fofb_stat[nonce][3]} {fofb/fofb_stat[nonce][4]} {fofb/fofb_stat[nonce][5]} {fofb/fofb_stat[nonce][6]} {fofb/fofb_stat[nonce][7]} {fofb/fofb_stat[nonce][8]} {fofb/fofb_stat[nonce][9]} {fofb/fofb_stat[nonce][10]} {fofb/fofb_stat[nonce][11]} {fofb/fofb_stat[nonce][12]} {fofb/fofb_stat[nonce][13]} {fofb/fofb_stat[nonce][14]} {fofb/fofb_stat[nonce][15]} {fofb/fofb_stat[nonce][16]} {fofb/fofb_stat[nonce][17]} {fofb/fofb_stat[nonce][18]} {fofb/fofb_stat[nonce][19]} {fofb/fofb_stat[nonce][20]} {fofb/fofb_stat[nonce][21]} {fofb/fofb_stat[nonce][22]} {fofb/fofb_stat[nonce][23]} {fofb/fofb_stat[nonce][24]} {fofb/fofb_stat[nonce][25]} {fofb/fofb_stat[nonce][26]} {fofb/fofb_stat[nonce][27]} {fofb/fofb_stat[nonce][28]} {fofb/fofb_stat[nonce][29]} {fofb/fofb_stat[nonce][30]} {fofb/fofb_stat[nonce][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe34]
set_property port_width 32 [get_debug_ports u_ila_0/probe34]
connect_debug_port u_ila_0/probe34 [get_nets [list {fofb/fofb_stat[packets_rcvd][0]} {fofb/fofb_stat[packets_rcvd][1]} {fofb/fofb_stat[packets_rcvd][2]} {fofb/fofb_stat[packets_rcvd][3]} {fofb/fofb_stat[packets_rcvd][4]} {fofb/fofb_stat[packets_rcvd][5]} {fofb/fofb_stat[packets_rcvd][6]} {fofb/fofb_stat[packets_rcvd][7]} {fofb/fofb_stat[packets_rcvd][8]} {fofb/fofb_stat[packets_rcvd][9]} {fofb/fofb_stat[packets_rcvd][10]} {fofb/fofb_stat[packets_rcvd][11]} {fofb/fofb_stat[packets_rcvd][12]} {fofb/fofb_stat[packets_rcvd][13]} {fofb/fofb_stat[packets_rcvd][14]} {fofb/fofb_stat[packets_rcvd][15]} {fofb/fofb_stat[packets_rcvd][16]} {fofb/fofb_stat[packets_rcvd][17]} {fofb/fofb_stat[packets_rcvd][18]} {fofb/fofb_stat[packets_rcvd][19]} {fofb/fofb_stat[packets_rcvd][20]} {fofb/fofb_stat[packets_rcvd][21]} {fofb/fofb_stat[packets_rcvd][22]} {fofb/fofb_stat[packets_rcvd][23]} {fofb/fofb_stat[packets_rcvd][24]} {fofb/fofb_stat[packets_rcvd][25]} {fofb/fofb_stat[packets_rcvd][26]} {fofb/fofb_stat[packets_rcvd][27]} {fofb/fofb_stat[packets_rcvd][28]} {fofb/fofb_stat[packets_rcvd][29]} {fofb/fofb_stat[packets_rcvd][30]} {fofb/fofb_stat[packets_rcvd][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe35]
set_property port_width 32 [get_debug_ports u_ila_0/probe35]
connect_debug_port u_ila_0/probe35 [get_nets [list {fofb/fofb_stat[ps1_setpt_flt][0]} {fofb/fofb_stat[ps1_setpt_flt][1]} {fofb/fofb_stat[ps1_setpt_flt][2]} {fofb/fofb_stat[ps1_setpt_flt][3]} {fofb/fofb_stat[ps1_setpt_flt][4]} {fofb/fofb_stat[ps1_setpt_flt][5]} {fofb/fofb_stat[ps1_setpt_flt][6]} {fofb/fofb_stat[ps1_setpt_flt][7]} {fofb/fofb_stat[ps1_setpt_flt][8]} {fofb/fofb_stat[ps1_setpt_flt][9]} {fofb/fofb_stat[ps1_setpt_flt][10]} {fofb/fofb_stat[ps1_setpt_flt][11]} {fofb/fofb_stat[ps1_setpt_flt][12]} {fofb/fofb_stat[ps1_setpt_flt][13]} {fofb/fofb_stat[ps1_setpt_flt][14]} {fofb/fofb_stat[ps1_setpt_flt][15]} {fofb/fofb_stat[ps1_setpt_flt][16]} {fofb/fofb_stat[ps1_setpt_flt][17]} {fofb/fofb_stat[ps1_setpt_flt][18]} {fofb/fofb_stat[ps1_setpt_flt][19]} {fofb/fofb_stat[ps1_setpt_flt][20]} {fofb/fofb_stat[ps1_setpt_flt][21]} {fofb/fofb_stat[ps1_setpt_flt][22]} {fofb/fofb_stat[ps1_setpt_flt][23]} {fofb/fofb_stat[ps1_setpt_flt][24]} {fofb/fofb_stat[ps1_setpt_flt][25]} {fofb/fofb_stat[ps1_setpt_flt][26]} {fofb/fofb_stat[ps1_setpt_flt][27]} {fofb/fofb_stat[ps1_setpt_flt][28]} {fofb/fofb_stat[ps1_setpt_flt][29]} {fofb/fofb_stat[ps1_setpt_flt][30]} {fofb/fofb_stat[ps1_setpt_flt][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe36]
set_property port_width 20 [get_debug_ports u_ila_0/probe36]
connect_debug_port u_ila_0/probe36 [get_nets [list {write_dacs/dac1/dac_data[0]} {write_dacs/dac1/dac_data[1]} {write_dacs/dac1/dac_data[2]} {write_dacs/dac1/dac_data[3]} {write_dacs/dac1/dac_data[4]} {write_dacs/dac1/dac_data[5]} {write_dacs/dac1/dac_data[6]} {write_dacs/dac1/dac_data[7]} {write_dacs/dac1/dac_data[8]} {write_dacs/dac1/dac_data[9]} {write_dacs/dac1/dac_data[10]} {write_dacs/dac1/dac_data[11]} {write_dacs/dac1/dac_data[12]} {write_dacs/dac1/dac_data[13]} {write_dacs/dac1/dac_data[14]} {write_dacs/dac1/dac_data[15]} {write_dacs/dac1/dac_data[16]} {write_dacs/dac1/dac_data[17]} {write_dacs/dac1/dac_data[18]} {write_dacs/dac1/dac_data[19]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe37]
set_property port_width 20 [get_debug_ports u_ila_0/probe37]
connect_debug_port u_ila_0/probe37 [get_nets [list {write_dacs/dac1/dac_setpt[0]} {write_dacs/dac1/dac_setpt[1]} {write_dacs/dac1/dac_setpt[2]} {write_dacs/dac1/dac_setpt[3]} {write_dacs/dac1/dac_setpt[4]} {write_dacs/dac1/dac_setpt[5]} {write_dacs/dac1/dac_setpt[6]} {write_dacs/dac1/dac_setpt[7]} {write_dacs/dac1/dac_setpt[8]} {write_dacs/dac1/dac_setpt[9]} {write_dacs/dac1/dac_setpt[10]} {write_dacs/dac1/dac_setpt[11]} {write_dacs/dac1/dac_setpt[12]} {write_dacs/dac1/dac_setpt[13]} {write_dacs/dac1/dac_setpt[14]} {write_dacs/dac1/dac_setpt[15]} {write_dacs/dac1/dac_setpt[16]} {write_dacs/dac1/dac_setpt[17]} {write_dacs/dac1/dac_setpt[18]} {write_dacs/dac1/dac_setpt[19]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe38]
set_property port_width 20 [get_debug_ports u_ila_0/probe38]
connect_debug_port u_ila_0/probe38 [get_nets [list {write_dacs/dac1/dac_setpt_raw[0]} {write_dacs/dac1/dac_setpt_raw[1]} {write_dacs/dac1/dac_setpt_raw[2]} {write_dacs/dac1/dac_setpt_raw[3]} {write_dacs/dac1/dac_setpt_raw[4]} {write_dacs/dac1/dac_setpt_raw[5]} {write_dacs/dac1/dac_setpt_raw[6]} {write_dacs/dac1/dac_setpt_raw[7]} {write_dacs/dac1/dac_setpt_raw[8]} {write_dacs/dac1/dac_setpt_raw[9]} {write_dacs/dac1/dac_setpt_raw[10]} {write_dacs/dac1/dac_setpt_raw[11]} {write_dacs/dac1/dac_setpt_raw[12]} {write_dacs/dac1/dac_setpt_raw[13]} {write_dacs/dac1/dac_setpt_raw[14]} {write_dacs/dac1/dac_setpt_raw[15]} {write_dacs/dac1/dac_setpt_raw[16]} {write_dacs/dac1/dac_setpt_raw[17]} {write_dacs/dac1/dac_setpt_raw[18]} {write_dacs/dac1/dac_setpt_raw[19]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe39]
set_property port_width 20 [get_debug_ports u_ila_0/probe39]
connect_debug_port u_ila_0/probe39 [get_nets [list {write_dacs/dac1/fofb_dac_setpt[0]} {write_dacs/dac1/fofb_dac_setpt[1]} {write_dacs/dac1/fofb_dac_setpt[2]} {write_dacs/dac1/fofb_dac_setpt[3]} {write_dacs/dac1/fofb_dac_setpt[4]} {write_dacs/dac1/fofb_dac_setpt[5]} {write_dacs/dac1/fofb_dac_setpt[6]} {write_dacs/dac1/fofb_dac_setpt[7]} {write_dacs/dac1/fofb_dac_setpt[8]} {write_dacs/dac1/fofb_dac_setpt[9]} {write_dacs/dac1/fofb_dac_setpt[10]} {write_dacs/dac1/fofb_dac_setpt[11]} {write_dacs/dac1/fofb_dac_setpt[12]} {write_dacs/dac1/fofb_dac_setpt[13]} {write_dacs/dac1/fofb_dac_setpt[14]} {write_dacs/dac1/fofb_dac_setpt[15]} {write_dacs/dac1/fofb_dac_setpt[16]} {write_dacs/dac1/fofb_dac_setpt[17]} {write_dacs/dac1/fofb_dac_setpt[18]} {write_dacs/dac1/fofb_dac_setpt[19]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe40]
set_property port_width 1 [get_debug_ports u_ila_0/probe40]
connect_debug_port u_ila_0/probe40 [get_nets [list fofb/ps1/data_rdy]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe41]
set_property port_width 1 [get_debug_ports u_ila_0/probe41]
connect_debug_port u_ila_0/probe41 [get_nets [list fofb/ps1/fofb_new]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe42]
set_property port_width 1 [get_debug_ports u_ila_0/probe42]
connect_debug_port u_ila_0/probe42 [get_nets [list fofb/fofb_packet]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe43]
set_property port_width 1 [get_debug_ports u_ila_0/probe43]
connect_debug_port u_ila_0/probe43 [get_nets [list fofb/fofb_rx_dv]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe44]
set_property port_width 1 [get_debug_ports u_ila_0/probe44]
connect_debug_port u_ila_0/probe44 [get_nets [list fofb/fofb_rx_dv_dly]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe45]
set_property port_width 1 [get_debug_ports u_ila_0/probe45]
connect_debug_port u_ila_0/probe45 [get_nets [list fofb/ps1/fofb_valid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe46]
set_property port_width 1 [get_debug_ports u_ila_0/probe46]
connect_debug_port u_ila_0/probe46 [get_nets [list fofb/ps1/mult_valid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe47]
set_property port_width 1 [get_debug_ports u_ila_0/probe47]
connect_debug_port u_ila_0/probe47 [get_nets [list tenkhz_trig]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_userclk2]
