

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list sys/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 20 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {ps_regs/reg_o[ps4_dac_setpt_offset][val][data][0]} {ps_regs/reg_o[ps4_dac_setpt_offset][val][data][1]} {ps_regs/reg_o[ps4_dac_setpt_offset][val][data][2]} {ps_regs/reg_o[ps4_dac_setpt_offset][val][data][3]} {ps_regs/reg_o[ps4_dac_setpt_offset][val][data][4]} {ps_regs/reg_o[ps4_dac_setpt_offset][val][data][5]} {ps_regs/reg_o[ps4_dac_setpt_offset][val][data][6]} {ps_regs/reg_o[ps4_dac_setpt_offset][val][data][7]} {ps_regs/reg_o[ps4_dac_setpt_offset][val][data][8]} {ps_regs/reg_o[ps4_dac_setpt_offset][val][data][9]} {ps_regs/reg_o[ps4_dac_setpt_offset][val][data][10]} {ps_regs/reg_o[ps4_dac_setpt_offset][val][data][11]} {ps_regs/reg_o[ps4_dac_setpt_offset][val][data][12]} {ps_regs/reg_o[ps4_dac_setpt_offset][val][data][13]} {ps_regs/reg_o[ps4_dac_setpt_offset][val][data][14]} {ps_regs/reg_o[ps4_dac_setpt_offset][val][data][15]} {ps_regs/reg_o[ps4_dac_setpt_offset][val][data][16]} {ps_regs/reg_o[ps4_dac_setpt_offset][val][data][17]} {ps_regs/reg_o[ps4_dac_setpt_offset][val][data][18]} {ps_regs/reg_o[ps4_dac_setpt_offset][val][data][19]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 24 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {ps_regs/reg_o[ps4_dac_setpt_gain][val][data][0]} {ps_regs/reg_o[ps4_dac_setpt_gain][val][data][1]} {ps_regs/reg_o[ps4_dac_setpt_gain][val][data][2]} {ps_regs/reg_o[ps4_dac_setpt_gain][val][data][3]} {ps_regs/reg_o[ps4_dac_setpt_gain][val][data][4]} {ps_regs/reg_o[ps4_dac_setpt_gain][val][data][5]} {ps_regs/reg_o[ps4_dac_setpt_gain][val][data][6]} {ps_regs/reg_o[ps4_dac_setpt_gain][val][data][7]} {ps_regs/reg_o[ps4_dac_setpt_gain][val][data][8]} {ps_regs/reg_o[ps4_dac_setpt_gain][val][data][9]} {ps_regs/reg_o[ps4_dac_setpt_gain][val][data][10]} {ps_regs/reg_o[ps4_dac_setpt_gain][val][data][11]} {ps_regs/reg_o[ps4_dac_setpt_gain][val][data][12]} {ps_regs/reg_o[ps4_dac_setpt_gain][val][data][13]} {ps_regs/reg_o[ps4_dac_setpt_gain][val][data][14]} {ps_regs/reg_o[ps4_dac_setpt_gain][val][data][15]} {ps_regs/reg_o[ps4_dac_setpt_gain][val][data][16]} {ps_regs/reg_o[ps4_dac_setpt_gain][val][data][17]} {ps_regs/reg_o[ps4_dac_setpt_gain][val][data][18]} {ps_regs/reg_o[ps4_dac_setpt_gain][val][data][19]} {ps_regs/reg_o[ps4_dac_setpt_gain][val][data][20]} {ps_regs/reg_o[ps4_dac_setpt_gain][val][data][21]} {ps_regs/reg_o[ps4_dac_setpt_gain][val][data][22]} {ps_regs/reg_o[ps4_dac_setpt_gain][val][data][23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 20 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {ps_regs/reg_o[ps3_dac_setpt_offset][val][data][0]} {ps_regs/reg_o[ps3_dac_setpt_offset][val][data][1]} {ps_regs/reg_o[ps3_dac_setpt_offset][val][data][2]} {ps_regs/reg_o[ps3_dac_setpt_offset][val][data][3]} {ps_regs/reg_o[ps3_dac_setpt_offset][val][data][4]} {ps_regs/reg_o[ps3_dac_setpt_offset][val][data][5]} {ps_regs/reg_o[ps3_dac_setpt_offset][val][data][6]} {ps_regs/reg_o[ps3_dac_setpt_offset][val][data][7]} {ps_regs/reg_o[ps3_dac_setpt_offset][val][data][8]} {ps_regs/reg_o[ps3_dac_setpt_offset][val][data][9]} {ps_regs/reg_o[ps3_dac_setpt_offset][val][data][10]} {ps_regs/reg_o[ps3_dac_setpt_offset][val][data][11]} {ps_regs/reg_o[ps3_dac_setpt_offset][val][data][12]} {ps_regs/reg_o[ps3_dac_setpt_offset][val][data][13]} {ps_regs/reg_o[ps3_dac_setpt_offset][val][data][14]} {ps_regs/reg_o[ps3_dac_setpt_offset][val][data][15]} {ps_regs/reg_o[ps3_dac_setpt_offset][val][data][16]} {ps_regs/reg_o[ps3_dac_setpt_offset][val][data][17]} {ps_regs/reg_o[ps3_dac_setpt_offset][val][data][18]} {ps_regs/reg_o[ps3_dac_setpt_offset][val][data][19]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 24 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {ps_regs/reg_o[ps3_dac_setpt_gain][val][data][0]} {ps_regs/reg_o[ps3_dac_setpt_gain][val][data][1]} {ps_regs/reg_o[ps3_dac_setpt_gain][val][data][2]} {ps_regs/reg_o[ps3_dac_setpt_gain][val][data][3]} {ps_regs/reg_o[ps3_dac_setpt_gain][val][data][4]} {ps_regs/reg_o[ps3_dac_setpt_gain][val][data][5]} {ps_regs/reg_o[ps3_dac_setpt_gain][val][data][6]} {ps_regs/reg_o[ps3_dac_setpt_gain][val][data][7]} {ps_regs/reg_o[ps3_dac_setpt_gain][val][data][8]} {ps_regs/reg_o[ps3_dac_setpt_gain][val][data][9]} {ps_regs/reg_o[ps3_dac_setpt_gain][val][data][10]} {ps_regs/reg_o[ps3_dac_setpt_gain][val][data][11]} {ps_regs/reg_o[ps3_dac_setpt_gain][val][data][12]} {ps_regs/reg_o[ps3_dac_setpt_gain][val][data][13]} {ps_regs/reg_o[ps3_dac_setpt_gain][val][data][14]} {ps_regs/reg_o[ps3_dac_setpt_gain][val][data][15]} {ps_regs/reg_o[ps3_dac_setpt_gain][val][data][16]} {ps_regs/reg_o[ps3_dac_setpt_gain][val][data][17]} {ps_regs/reg_o[ps3_dac_setpt_gain][val][data][18]} {ps_regs/reg_o[ps3_dac_setpt_gain][val][data][19]} {ps_regs/reg_o[ps3_dac_setpt_gain][val][data][20]} {ps_regs/reg_o[ps3_dac_setpt_gain][val][data][21]} {ps_regs/reg_o[ps3_dac_setpt_gain][val][data][22]} {ps_regs/reg_o[ps3_dac_setpt_gain][val][data][23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 20 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {ps_regs/reg_o[ps2_dac_setpt_offset][val][data][0]} {ps_regs/reg_o[ps2_dac_setpt_offset][val][data][1]} {ps_regs/reg_o[ps2_dac_setpt_offset][val][data][2]} {ps_regs/reg_o[ps2_dac_setpt_offset][val][data][3]} {ps_regs/reg_o[ps2_dac_setpt_offset][val][data][4]} {ps_regs/reg_o[ps2_dac_setpt_offset][val][data][5]} {ps_regs/reg_o[ps2_dac_setpt_offset][val][data][6]} {ps_regs/reg_o[ps2_dac_setpt_offset][val][data][7]} {ps_regs/reg_o[ps2_dac_setpt_offset][val][data][8]} {ps_regs/reg_o[ps2_dac_setpt_offset][val][data][9]} {ps_regs/reg_o[ps2_dac_setpt_offset][val][data][10]} {ps_regs/reg_o[ps2_dac_setpt_offset][val][data][11]} {ps_regs/reg_o[ps2_dac_setpt_offset][val][data][12]} {ps_regs/reg_o[ps2_dac_setpt_offset][val][data][13]} {ps_regs/reg_o[ps2_dac_setpt_offset][val][data][14]} {ps_regs/reg_o[ps2_dac_setpt_offset][val][data][15]} {ps_regs/reg_o[ps2_dac_setpt_offset][val][data][16]} {ps_regs/reg_o[ps2_dac_setpt_offset][val][data][17]} {ps_regs/reg_o[ps2_dac_setpt_offset][val][data][18]} {ps_regs/reg_o[ps2_dac_setpt_offset][val][data][19]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 24 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {ps_regs/reg_o[ps2_dac_setpt_gain][val][data][0]} {ps_regs/reg_o[ps2_dac_setpt_gain][val][data][1]} {ps_regs/reg_o[ps2_dac_setpt_gain][val][data][2]} {ps_regs/reg_o[ps2_dac_setpt_gain][val][data][3]} {ps_regs/reg_o[ps2_dac_setpt_gain][val][data][4]} {ps_regs/reg_o[ps2_dac_setpt_gain][val][data][5]} {ps_regs/reg_o[ps2_dac_setpt_gain][val][data][6]} {ps_regs/reg_o[ps2_dac_setpt_gain][val][data][7]} {ps_regs/reg_o[ps2_dac_setpt_gain][val][data][8]} {ps_regs/reg_o[ps2_dac_setpt_gain][val][data][9]} {ps_regs/reg_o[ps2_dac_setpt_gain][val][data][10]} {ps_regs/reg_o[ps2_dac_setpt_gain][val][data][11]} {ps_regs/reg_o[ps2_dac_setpt_gain][val][data][12]} {ps_regs/reg_o[ps2_dac_setpt_gain][val][data][13]} {ps_regs/reg_o[ps2_dac_setpt_gain][val][data][14]} {ps_regs/reg_o[ps2_dac_setpt_gain][val][data][15]} {ps_regs/reg_o[ps2_dac_setpt_gain][val][data][16]} {ps_regs/reg_o[ps2_dac_setpt_gain][val][data][17]} {ps_regs/reg_o[ps2_dac_setpt_gain][val][data][18]} {ps_regs/reg_o[ps2_dac_setpt_gain][val][data][19]} {ps_regs/reg_o[ps2_dac_setpt_gain][val][data][20]} {ps_regs/reg_o[ps2_dac_setpt_gain][val][data][21]} {ps_regs/reg_o[ps2_dac_setpt_gain][val][data][22]} {ps_regs/reg_o[ps2_dac_setpt_gain][val][data][23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 20 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {ps_regs/reg_o[ps1_dac_setpt_offset][val][data][0]} {ps_regs/reg_o[ps1_dac_setpt_offset][val][data][1]} {ps_regs/reg_o[ps1_dac_setpt_offset][val][data][2]} {ps_regs/reg_o[ps1_dac_setpt_offset][val][data][3]} {ps_regs/reg_o[ps1_dac_setpt_offset][val][data][4]} {ps_regs/reg_o[ps1_dac_setpt_offset][val][data][5]} {ps_regs/reg_o[ps1_dac_setpt_offset][val][data][6]} {ps_regs/reg_o[ps1_dac_setpt_offset][val][data][7]} {ps_regs/reg_o[ps1_dac_setpt_offset][val][data][8]} {ps_regs/reg_o[ps1_dac_setpt_offset][val][data][9]} {ps_regs/reg_o[ps1_dac_setpt_offset][val][data][10]} {ps_regs/reg_o[ps1_dac_setpt_offset][val][data][11]} {ps_regs/reg_o[ps1_dac_setpt_offset][val][data][12]} {ps_regs/reg_o[ps1_dac_setpt_offset][val][data][13]} {ps_regs/reg_o[ps1_dac_setpt_offset][val][data][14]} {ps_regs/reg_o[ps1_dac_setpt_offset][val][data][15]} {ps_regs/reg_o[ps1_dac_setpt_offset][val][data][16]} {ps_regs/reg_o[ps1_dac_setpt_offset][val][data][17]} {ps_regs/reg_o[ps1_dac_setpt_offset][val][data][18]} {ps_regs/reg_o[ps1_dac_setpt_offset][val][data][19]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 24 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {ps_regs/reg_o[ps1_dac_setpt_gain][val][data][0]} {ps_regs/reg_o[ps1_dac_setpt_gain][val][data][1]} {ps_regs/reg_o[ps1_dac_setpt_gain][val][data][2]} {ps_regs/reg_o[ps1_dac_setpt_gain][val][data][3]} {ps_regs/reg_o[ps1_dac_setpt_gain][val][data][4]} {ps_regs/reg_o[ps1_dac_setpt_gain][val][data][5]} {ps_regs/reg_o[ps1_dac_setpt_gain][val][data][6]} {ps_regs/reg_o[ps1_dac_setpt_gain][val][data][7]} {ps_regs/reg_o[ps1_dac_setpt_gain][val][data][8]} {ps_regs/reg_o[ps1_dac_setpt_gain][val][data][9]} {ps_regs/reg_o[ps1_dac_setpt_gain][val][data][10]} {ps_regs/reg_o[ps1_dac_setpt_gain][val][data][11]} {ps_regs/reg_o[ps1_dac_setpt_gain][val][data][12]} {ps_regs/reg_o[ps1_dac_setpt_gain][val][data][13]} {ps_regs/reg_o[ps1_dac_setpt_gain][val][data][14]} {ps_regs/reg_o[ps1_dac_setpt_gain][val][data][15]} {ps_regs/reg_o[ps1_dac_setpt_gain][val][data][16]} {ps_regs/reg_o[ps1_dac_setpt_gain][val][data][17]} {ps_regs/reg_o[ps1_dac_setpt_gain][val][data][18]} {ps_regs/reg_o[ps1_dac_setpt_gain][val][data][19]} {ps_regs/reg_o[ps1_dac_setpt_gain][val][data][20]} {ps_regs/reg_o[ps1_dac_setpt_gain][val][data][21]} {ps_regs/reg_o[ps1_dac_setpt_gain][val][data][22]} {ps_regs/reg_o[ps1_dac_setpt_gain][val][data][23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list write_dacs/tenkhz_trig]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list tenkhz_trig]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets pl_clk0]
